### ISSUE TITLE
Bitcode problem

### ISSUE THREAD

**Issue by lemhell** [color-tv/Color-tvOS-SDK#4]
Hello, I'm trying to integrate your SDK into my Apple TV app, but getting the following error:
`COLORAdFramework.framework/COLORAdFramework was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64`
I was trying to archive an ipa when this error occured. Did you not build your framework withoud bitcode enabled? (I think this is highly unlikely, because bitcode is required for Apple TV)
Or did I just do something wrong?
Thank you in advance.

**Comment by jordanj-pl** [comment]
Thank you for your feedback, we investigated the issue and our building scripts have been modified. Please download the latest binary to resolve this issue.
