### ISSUE TITLE
TVML: Determine when ad has completed

### ISSUE THREAD

**Issue by jermaine150** [color-tv/Color-tvOS-SDK#9]
When a user presses a button in my app, I would like to show an ad, and after the ad has completed continue with the action behind the button.

When I implement the SDK in a Swift application there is a callback available to determine whether an ad has completed:

`COLORAdController.sharedAdController().adViewControllerForPlacement(placement, withCompletion:{ (vc , error) in
            ...

            vc.adCompleted = { (videoWatched) in
                self.dismissViewControllerAnimated(true, completion: nil)
            }

            ...
        }, expirationHandler: { (expiredVc) in
            //If you kept a reference to COLORAdViewController but haven't shown it yet, you should discard it now
        })`

However, when I use the TVML equivalent there is no such method:
`COLORAdController.sharedAdController().prepareAdForPlacementWithCompletionAndExpirationHandler("MainMenu", function(success) {
        if(success) {
            console.log("AD prepared");
            COLORAdController.sharedAdController().showLastAd();
        } else {
            console.log("AD NOT prepared");
        }
    }, function() {
        console.log("AD expired");
    }
);`

 I can show the ad with 'COLORAdController.sharedAdController().showLastAd()' but there is no way to check whether the ad has completed. Is it possible to add an event handler for this?

**Comment by jordanj-pl** [comment]
Thank you for contact with us. We appreciate feedback from developers who are to integrate our SDK. I have added it as feature request.

We will add a new method showLastAdWithCompletionHandler(function(watched){
});

It should be available along with one of the next releases, hopefully in the beginning of next week.

I will inform you accordingly.

Best regards,
Jordan Jasinski
Lead tvOS developer

**Comment by jermaine150** [comment]
Thanks! I'm looking forward to the next release.

**Comment by jordanj-pl** [comment]
Newly released version 1.6.2 contains the additional callback. You can find details in README file. Enjoy!
